### ISSUE TITLE
create a manifest file for each KG-COVID build

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-covid-19#130]
output stats of node and edge count by source

output stats of edges between sets of nodes from different sources (can be all pairwise to start, just want lay of the land)

over time and transition this to specific rules that trigger errors or warnings

**Comment by cmungall** [comment]
Consider also a Changes.md in the root of the GH repo. This could be bundled into each release.

**Comment by realmarcin** [comment]
On Mon, May 18, 2020 at 11:52 AM Marcin Joachimiak <marcinjoachimiak@gmail.com> wrote:
We've had some discussions about various stats and summaries around KG-COVID and the KGX pipeline. There are a few pieces so here goes:

1. Stats for the upstream input source files (could also be in context of a larger source they arrive from, eg ChEMBL vs ChEMBL-viral). This is just counts of nodes and edges.

You mean stats for the ingested source files rather than the source files themselves?

Yes, this could just be the counts pre-merge
 
2. Stats for the KGX process, so redundancy and merging for now as I understand it. I think one useful metric here would be how many nodes and edges get 'dropped' from each input. Also if there is redundancy, what choices were made to preserve/drop -- say in case where redundant edges are from different sources?

very good point

we could go to town and create a PROV graph and annotate each relevant part with statistics using the void vocab.. probably overkill for us now, but something to recommend at SRI level?

Maybe for now, just something like python logging, and attaching INFO-level to the release?

I really like the idea of preserving/recording choices that were made

One nice thing scigraph does is record original source_subject and source_object values
 
3. Stats for the KG-COVID graph build. Here there are the global graph stats, but also how many edges link across the input data sources.

great, yes
 
How can we improve/streamline the above?
Am I missing anything?

And any thoughts on how to optimize 1-3? Eg would the graph build stats for 3. want to live in KGX stats for 2.?

good point. If we run stats off the final product, it's harder to calculate for 1, since we have lost information

maybe that's ok in the short term
 
Some of these stats would be nice to compute with a graph query, especially 3.

yep
 
I can help with some of this depending on what else is going on.

This would be useful. Let's figure out the mechanism (sparql/sql/cypher over an engine; pandas over the files; ad-hoc unix cli tools; custom code over nx (does KGX do some summary stats Deepak?)). May be hybrid

Incremental is good here
 
best,
marcin

**Comment by deepakunni3** [comment]
A lot of the stats generation code can live in KGX.  But a few questions before I start implementing some of these:

1. what format do we want the stats to be?
2. When merging edges do we log what happens for each edge? OR just a summary stating 4000 edges merged between source X and source Y.
3. Stats for upstream sources are very easy to generate. Again, where would the output go? Do we generate a log for merge where,
    - we first calculates stats for each source pre-merge
    - then logs the merge stats during the merge
    - then logs the final graph stats post-merge

KGX does summary stats but needs some TLC before it can be used.

**Comment by cmungall** [comment]
Good Q

The format should be computable, but also easy to grok by a human

I suggest a per-graph tsv or yaml with keys such as 'number_of_nodes'. There can be a separate data dictionary for this (e.g. json-ld context) but this can come later.

It may be more convenient to have one single summary file. Here they key would have to be compound of graph and statistic.

We should have a standard naming convention for the graphs. E.g cheml-ingest, kg-covid-19-merged

**Comment by justaddcoffee** [comment]
My $0.02: 

> what format do we want the stats to be?

No strong feelings here - maybe YAML or JSON? YAML might be easier for humans to read

> When merging edges do we log what happens for each edge? OR just a summary stating 4000 edges merged between source X and source Y.

I'd vote for the latter for now - logging what happens to each edge in a big graph might be painful. 

> Stats for upstream sources are very easy to generate. Again, where would the output go? Do we generate a log for merge where,

If we had this stats, I'd put these in data/transform/ and data/merged/, and we can generate pretty markdown from them

**Comment by deepakunni3** [comment]
Awesome! Thanks @cmungall @justaddcoffee 

Those should be easy to implement.

**Comment by deepakunni3** [comment]
How about this:
```yml
graph_name: test graph
edge_stats:
  count_by_edge_label:
    biolink:has_gene_product: 17837
    biolink:interacts_with: 982162
    unknown: 0
  count_by_spo:
    biolink:Gene-biolink:has_gene_product-unknown: 17837
    unknown-biolink:interacts_with-unknown: 982162
  edge_labels:
  - biolink:has_gene_product
  - biolink:interacts_with
  total_edges: 999999
node_stats:
  count_by_category:
    Biolink:Gene: 119
    Biolink:OrganismalEntity: 6
    biolink:Drug: 33623
    biolink:Gene: 24491
    biolink:PhenotypicFeature: 14965
    biolink:Protein: 17871
    unknown: 21850
  node_categories:
  - Biolink:OrganismalEntity
  - biolink:PhenotypicFeature
  - biolink:Drug
  - biolink:Gene
  - Biolink:Gene
  - biolink:Protein
  total_nodes: 112925

```
