### ISSUE TITLE
Add filter in merge step (via entry in merge.yaml) for node and edge type

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#234]
Per convo with @deepakunni3, KGX now supports filtering by node and edge type, so we could easily support filtering for node and edge type

```
target:
   drug-central:
      type: tsv
      filename:
         - data/transformed/drug_central/nodes.tsv
         - data/transformed/drug_central/edges.tsv
       node_filters:          
              category:             
                   - biolink:Gene             
                   - biolink:Protein       
```
